### ISSUE TITLE
Not available on npm

### ISSUE THREAD

**Issue by Armaldio** [retejs/connection-mastery-plugin#1]
I've also tried building myself by the build failed

**Comment by Ni55aN** [comment]
https://www.npmjs.com/package/rete-connection-mastery-plugin

**Comment by Armaldio** [comment]
Great!

Built files seems not to be published tho

**Comment by Armaldio** [comment]
I got this error with webpack:  
```
This dependency was not found:

* rete-connection-plugin/types in ./node_modules/rete-connection-mastery-plugin/build/connection-mastery-plugin.esm.js

To install it, you can run: npm install --save rete-connection-plugin/types
```

**Comment by Ni55aN** [comment]
What version of rete-connection-plugin do you have installed?

**Comment by Armaldio** [comment]
Last version available
`"rete-connection-plugin": "^0.6.4",`

**Comment by Ni55aN** [comment]
Is the problem actual?

**Comment by bCliks** [comment]
@Ni55aN  Yes. `rete-connection-plugin/types` dependency was not found in `rete-connection-mastery-plugin`

```
This dependency was not found:

* rete-connection-plugin/types in ./node_modules/rete-connection-mastery-plugin/build/connection-mastery-plugin.esm.js

To install it, you can run: npm install --save rete-connection-plugin/types
```

**Comment by Ni55aN** [comment]
@bCliks  how to reproduce?

**Comment by Ni55aN** [comment]
I have reproduced. You should to install latest version of `rete-connection-plugin`.
`rete-connection-plugin` dependency in matery plugin is outdated

**Comment by Ni55aN** [comment]
By the way, its strange, because 0.6.3 has "types" folder (https://www.jsdelivr.com/package/npm/rete-connection-plugin?version=0.6.3), but it missed in node_modules

**Comment by Ni55aN** [comment]
Try to update this plugin to v0.2.1

**Comment by bCliks** [comment]
@Ni55aN Thanks for the quick update. unfortunately still same error. 
Tried with `v0.2.1` of this plugin. Still it says missing `rete-connection-plugin/types` dependency

![image](https://user-images.githubusercontent.com/3747809/61208827-e33ba700-a715-11e9-8805-e74eab9744e7.png)

**Comment by Ni55aN** [comment]
@bCliks do you have types folder in node_modules/rete-connection-plugin?

**Comment by bCliks** [comment]
@Ni55aN  yes. I have! 

![image](https://user-images.githubusercontent.com/3747809/61211685-e20e7800-a71d-11e9-9a36-bb404cd449d9.png)

**Comment by Ni55aN** [comment]
I found issue, will fix it

**Comment by Ni55aN** [comment]
v0.2.2 should works fine in JS projects

P.S. I was building it in my TS projects and didn't receive this error

**Comment by bCliks** [comment]
Thank you! working 👍
